name: Go

on: [ push, pull_request ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v5
      with:
        go-version: '1.23.0-rc.1'
    - name: Get dependencies
      run: go mod download
    - name: Test
      run: go test -race -v -coverprofile=profile.cov ./...
    - name: Upload Coverage
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: profile.cov
